spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9291

logging:
  level:
    root: info
    org.apache.zookeeper: error
    org.apache.kafka: error
    io.spring.scs_kotlin_sample: debug